### ISSUE TITLE
Attribute error while creating configuration

### ISSUE THREAD

**Issue by cononco99** [philliphall/plaid2qfx#1]
python plaid2qfx.py -s
Looks like you don't have a configuration file yet, so I will create one. It will be encrypted using the following randomly generated key that you are responsible for protecting:
25899636666d7e3c5e5a3b4a78feb00af1ed6ac27ea2dbb924ddd548e15429ab
Press enter once you have saved this key.
Please provide your Plaid API client_id: vvvv
Please provide your client API Secret:
Where would you like output files stored? [/home/cononco99]:
Traceback (most recent call last):
  File "/home/cononco99/plaid2qfx/plaid2qfx.py", line 84, in <module>
    plaid_api_configuration = plaid.Configuration(
                              ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'plaid' has no attribute 'Configuration'. Did you mean: 'configuration'?

**Comment by philliphall** [comment]
Thank you! 

hmmmm, been doing my development in Windows, will have to do some Linux testing. Perhaps a difference in capitalization handling? Or in how the modules are imported and referenced... probably Thursday or later before I get a look.

**Comment by cononco99** [comment]
Before you do anything, I'll try setting up my dev environment again.    It took me some trial/error and I might have messed something up.    Probably will get to that tomorrow morning.

**Comment by cononco99** [comment]
Started over from scratch and did not see that error.   I suspect it was from having pip installed plaid before plaid-python (just a guess though).  This time I got this backtrace which looks bad but may be just failing to connect to plaid (I just made up client_id and secret)

~/plaid2qfx$ python plaid2qfx.py -s
Looks like you don't have a configuration file yet, so I will create one. It will be encrypted using the following randomly generated key that you are responsible for protecting:
8aeba41da7e4516f408e8ba857067f0bf739f7757e19cc4acccce1b81534e445
Press enter once you have saved this key.
Please provide your Plaid API client_id: sdfsd
Please provide your client API Secret:
Where would you like output files stored? [/home/cononco99]:
Doesn't look like we have any accounts defined yet. Let's set one up.
For the purposes of this script, what label would you like to give this linked account? sofi
Traceback (most recent call last):
  File "/home/cononco99/plaid2qfx/plaid2qfx.py", line 667, in <module>
    main()
  File "/home/cononco99/plaid2qfx/plaid2qfx.py", line 114, in main
    link_name = link_account()
                ^^^^^^^^^^^^^^
  File "/home/cononco99/plaid2qfx/plaid2qfx.py", line 243, in link_account
    response = client.link_token_create(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api/plaid_api.py", line 19730, in link_token_create
    return self.link_token_create_endpoint.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api_client.py", line 205, in __call_api
    raise e
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api_client.py", line 198, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/api_client.py", line 467, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/rest.py", line 270, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cononco99/venv/lib/python3.11/site-packages/plaid/rest.py", line 229, in request
    raise ApiException(http_resp=r)
plaid.exceptions.ApiException: Status Code: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 16 Aug 2023 02:53:55 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '322', 'Connection': 'keep-alive'})
HTTP response body: {
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "client_id must be a properly formatted, non-empty string",
  "error_type": "INVALID_REQUEST",
  "request_id": "I0BnN0xtXR3QlvQ",
  "suggested_action": null
}

**Comment by philliphall** [comment]
Definitely will want to add some error handling. plaid-python appears to offer good ways of handling and interpreting error responses from Plaid... will take a little bit to learn how to incorporate those and implement. Good catch!

**Comment by cononco99** [comment]
Probably user error
