### ISSUE TITLE
plaid (incorrectly) reports positive balance for credit card.

### ISSUE THREAD

**Issue by cononco99** [philliphall/plaid2qfx#8]
Plaid reports a positive balance for a credit card that holds debt but this should be a negative balance - the magnitude is right but the sign is wrong.

If you download a .qfx file for a credit card you can compare and see that the balance in the qfx file is negative (as it should be and as Quicken expects).

If you import a .qfx file created by plaid2qfx with the positive balance, the import will work but you will be unable to reconcile to the online balance.

**Comment by philliphall** [comment]
Perfect, thank you for identifying and extra thank you for the pull request! Merged and tested successfully on my end :-)
